 <?php $item = $this->getNews(); ?>
<?php if (empty($item)):?>
    <p xmlns="http://www.w3.org/1999/html">No news available<p>
<?php else: ?>
    <h3><?php
        if (isset($item['title'])) {
            echo $item['title'];
        }
        ?></h3>   
        <p style="font-size: small;color: #777">published on: 
        <?php echo date('M jS, Y', strtotime($item['update_time'])); ?>
        <a href="/news">Back to all news</a>
    </p>
    <div>
    <span style="float: left">
    <img src="<?php echo Mage::getBaseUrl('media') . 'news' . DS .
        $item['filename'] ?>" alt="<?php echo $item['title']?>"
         width="128"
         height="128"
         style="border: 1px solid#d5d5d5;
    padding:3px;
    margin-right: 10px;" />
    </span>
    <span>
        <p>
            <?php echo $item['content']; ?></p>
    </span>
        <p style="clear: both">
        </p>
    </div>
    <a href="<?php
    echo $this->getBaseUrl('')
    ?>
         news">Back to all news</a>
<?php endif; ?> 